
@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Movie test
GET {{baseUrl}}/api/test/343611

### Movie
GET {{baseUrl}}/api/movies/343611

### Actor
GET {{baseUrl}}/api/actors/343611