
@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Movie complete
GET {{baseUrl}}/api/moviedata/343611

### Actor
GET {{baseUrl}}/api/actors/343611

### Movie
GET {{baseUrl}}/api/movies/343611